package SeparateDataFromBehaviour.domain

sealed trait ErrorSettingSurrogateId
final case object SurrogateIdAlreadySet extends ErrorSettingSurrogateId
final case object SurrogateIdCannotSetToNone extends ErrorSettingSurrogateId